eu_dev_compensation:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: dev
      threads: 4
      timeout_seconds: 300
      location: EU

    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: prod
      threads: 4
      timeout_seconds: 300
      location: EU
