{% macro is_it_job(job_title_col) %}
    (
        -- roles
        {{ job_title_col }} like '%developer%'
        or {{ job_title_col }} like '%engineer%'
        or {{ job_title_col }} like '%software%'
        or {{ job_title_col }} like '%architect%'
        or {{ job_title_col }} like '%analyst%'
        or {{ job_title_col }} like '%tester%'
        or {{ job_title_col }} like '% qa %'
        or {{ job_title_col }} like '%devops%'
        or {{ job_title_col }} like '% sre %'
        or {{ job_title_col }} like '%tech lead%'
        -- stack
        or {{ job_title_col }} like '%python%'
        or {{ job_title_col }} like '%java%'
        or {{ job_title_col }} like '%javascript%'
        or {{ job_title_col }} like '%typescript%'
        or {{ job_title_col }} like '%golang%'
        or {{ job_title_col }} like '%ruby%'
        or {{ job_title_col }} like '%rust%'
        or {{ job_title_col }} like '%swift%'
        or {{ job_title_col }} like '%react%'
        or {{ job_title_col }} like '%angular%'
        or {{ job_title_col }} like '%vue%'
        or {{ job_title_col }} like '% php%'
        -- domains
        or {{ job_title_col }} like '%backend%'
        or {{ job_title_col }} like '%back-end%'
        or {{ job_title_col }} like '%frontend%'
        or {{ job_title_col }} like '%front-end%'
        or {{ job_title_col }} like '%fullstack%'
        or {{ job_title_col }} like '%full-stack%'
        or {{ job_title_col }} like '%mobile%'
        or {{ job_title_col }} like '% ios %'
        or {{ job_title_col }} like '%android%'
        or {{ job_title_col }} like '%cloud%'
        or {{ job_title_col }} like '%security%'
        or {{ job_title_col }} like '%database%'
        or {{ job_title_col }} like '% dba %'
        or {{ job_title_col }} like '%infrastructure%'
        or {{ job_title_col }} like '%platform%'
        or {{ job_title_col }} like '%network%'
        or {{ job_title_col }} like '%sysadmin%'
        or {{ job_title_col }} like '%it support%'
        or {{ job_title_col }} like '%data%'
        -- slovak terms
        or {{ job_title_col }} like '%programátor%'
        or {{ job_title_col }} like '%vývojár%'
        or {{ job_title_col }} like '%analytik%'
        or {{ job_title_col }} like '%administrátor%'
        or {{ job_title_col }} like '%správca%'
        or {{ job_title_col }} like '%technik%'
    )
{% endmacro %}
